// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package user

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitAPI(db *gorm.DB) *API {
	repository := ProvideRepository(db)
	jwtService := ProvideJWTService()
	service := ProvideService(repository, jwtService)
	api := ProvideAPI(service)
	return api
}

func ProvideAuthMiddleware(db *gorm.DB) gin.HandlerFunc {
	repository := ProvideRepository(db)
	jwtService := ProvideJWTService()
	service := ProvideService(repository, jwtService)
	handlerFunc := AuthMiddleware(service)
	return handlerFunc
}

// wire.go:

var set = wire.NewSet(ProvideService, ProvideRepository, ProvideJWTService)
