name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o food_ordering_api

    - name: Upload docs
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PROD_API }}
        username: ${{ secrets.PROD_USERNAME }}
        password: ${{ secrets.PROD_PASSWORD }}
        source: "docs/*"
        target: "~/src/api.food-ordering.app/docs"

    - name: Upload API
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PROD_API }}
        username: ${{ secrets.PROD_USERNAME }}
        password: ${{ secrets.PROD_PASSWORD }}
        source: "food_ordering_api"
        target: "~/src/api.food-ordering.app"

    - name: Restart API
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_API }}
        username: ${{ secrets.PROD_USERNAME }}
        password: ${{ secrets.PROD_PASSWORD }}
        script: sudo systemctl restart food_ordering_api.service
